[package]
name = "generator"
version = "0.1.0"
authors = ["David Zmick <david@dpzmick.com>"]
edition = "2018"

[dependencies]
vkxml = { path = "../vkxml/" }
mustache = "*"
serde = { version = "1.0", features = ["derive"] }