[package]
name = "winds-of-chime"
version = "0.1.0"
authors = ["David Zmick <dpzmick@gmail.com>"]
edition = "2018"

[dependencies]
ash   = "0.29.0"
winit = "0.19.3"

[profile.dev]
opt-level     = 0
lto           = false
codegen-units = 16
incremental   = true
