[package]
name = "vk_functions"
version = "0.1.0"
authors = ["David Zmick <david@dpzmick.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies.syn]
version = "1.0.16"
features = ["full"]

[dependencies.quote]
version = "1.0.3"
